name: Blaire
favicon: null
layout_spectrum: 0.75102
typography_spectrum: 0.25149
title: Blaire
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#000000'
    - '#728aa2'
    - '#b3b9c1'
    - '#525e6b'
  brandStrength: 0.9038332893978804
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.5
purpose: []
