name: Blaire
favicon: null
layout_spectrum: 0.8772212122566998
typography_spectrum: 0.5752625488676131
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9038332893978804
  lightness: 0.7336556154768914
  saturation: 0.10283279465511441
  rhythmicContrast: 0.1985147122759372
purpose: []
